# Generated by Django 3.1.1 on 2021-03-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0004_auto_20210310_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergies',
            name='name',
            field=models.CharField(default=None, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='allergies',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loginApp.allergies'),
        ),
    ]
