# Generated by Django 3.1.1 on 2021-03-17 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0005_auto_20210310_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginApp.recipe'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='storage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='loginApp.storage'),
        ),
    ]
