# Generated by Django 3.1.1 on 2021-03-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0008_preingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PreIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.IntegerField()),
                ('measure', models.CharField(max_length=200)),
                ('multiply', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PreIngredient',
        ),
    ]
