# Generated by Django 3.2.4 on 2021-07-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0011_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rfid_hash',
            field=models.CharField(blank=True, default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rfid_token',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
