# Generated by Django 3.2.6 on 2021-08-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0012_auto_20210703_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('crd', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
            ],
        ),
    ]
