# Generated by Django 3.2.6 on 2021-08-15 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0015_auto_20210815_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='crd',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 17, 33, 5, 211158)),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 17, 35, 5, 211158)),
        ),
    ]
