# Generated by Django 3.2.6 on 2021-08-15 16:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0016_auto_20210815_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='crd',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 16, 50, 31, 296092, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 16, 52, 31, 296092, tzinfo=utc)),
        ),
    ]
