# Generated by Django 3.2.6 on 2021-08-17 07:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0025_alter_apimodel_valid_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='rfid_token',
            new_name='rfid_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rfid_hash',
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 17, 7, 31, 19, 827233, tzinfo=utc)),
        ),
    ]
