# Generated by Django 3.2.6 on 2021-09-14 13:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0026_auto_20210817_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='storage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginApp.storage'),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 14, 13, 40, 31, 131913, tzinfo=utc)),
        ),
    ]
