# Generated by Django 3.2.6 on 2021-09-17 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0027_auto_20210914_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='storage',
            field=models.OneToOneField(null=True, on_delete=models.SET_NULL, to='loginApp.storage'),
        ),
        migrations.AlterField(
            model_name='apimodel',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 9, 22, 37, 565901, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='allergies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginApp.allergies'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='loginApp.category'),
        ),
    ]
