# Generated by Django 3.2.6 on 2021-09-25 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0028_auto_20210917_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apimodel',
            name='valid_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 25, 12, 10, 40, 723462, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rfid_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
